"use client";

import { useMemo, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useTexture, Float, MeshTransmissionMaterial } from "@react-three/drei";
import * as THREE from "three";

// Control points for the urn's outer profile (radius, y) — from base to lip.
// These are PROFILE GUIDES; the actual lathe profile is generated by sampling
// a Catmull-Rom spline through these, so the surface is smooth, not faceted.
const URN_CONTROL_POINTS: Array<[number, number]> = [
  [0.001, -1.05],
  [0.36, -1.05],
  [0.45, -1.03],
  [0.5, -0.98],
  [0.46, -0.9],
  [0.4, -0.82],
  [0.42, -0.72],
  [0.55, -0.58],
  [0.72, -0.36],
  [0.84, -0.1],
  [0.87, 0.16],
  [0.83, 0.36],
  [0.7, 0.55],
  [0.55, 0.7],
  [0.46, 0.82],
  [0.46, 0.92],
  [0.55, 1.0],
  [0.66, 1.06],
  [0.66, 1.1],
  [0.6, 1.12],
  [0.001, 1.12],
];

// Sample count along the spline — higher = smoother silhouette.
const PROFILE_SAMPLES_HIGH = 220;
const PROFILE_SAMPLES_LOW = 110;

function sampleProfile(controls: Array<[number, number]>, samples: number) {
  const pts = controls.map(([x, y]) => new THREE.Vector2(x, y));
  const curve = new THREE.SplineCurve(pts);
  return curve.getPoints(samples);
}

type Props = { quality: "low" | "high" };

export function MarbleSculpture({ quality }: Props) {
  const ref = useRef<THREE.Group>(null);
  const orbRef = useRef<THREE.Mesh>(null);
  const inner = useRef<THREE.Mesh>(null);

  const marbleTexture = useTexture("/images/generated/background-parchment-marble.webp");
  marbleTexture.wrapS = THREE.RepeatWrapping;
  marbleTexture.wrapT = THREE.RepeatWrapping;
  marbleTexture.colorSpace = THREE.SRGBColorSpace;
  marbleTexture.repeat.set(1.5, 2.5);
  marbleTexture.anisotropy = 8;

  const radialSegments = quality === "low" ? 96 : 192;
  const profileSamples = quality === "low" ? PROFILE_SAMPLES_LOW : PROFILE_SAMPLES_HIGH;

  const vesselPoints = useMemo(
    () => sampleProfile(URN_CONTROL_POINTS, profileSamples),
    [profileSamples],
  );

  // No per-frame rotation — the object stays still. Camera motion (driven by
  // scroll in SceneContent) provides the only perspective change. This kills
  // the "highlight sliding across the surface" flicker.
  useFrame(() => {});

  return (
    <group ref={ref} position={[0, -0.15, 0]}>
      {/* Classical urn — body */}
      <mesh ref={inner} castShadow receiveShadow>
        <latheGeometry args={[vesselPoints, radialSegments]} />
        <meshPhysicalMaterial
          map={marbleTexture}
          color="#EBE4D2"
          roughness={0.34}
          metalness={0.02}
          clearcoat={0.42}
          clearcoatRoughness={0.22}
          sheen={0.28}
          sheenRoughness={0.7}
          sheenColor="#E8D6B0"
          envMapIntensity={0.65}
          flatShading={false}
        />
      </mesh>

      {/* Plinth foot — smooth cylinder with subtle taper */}
      <group position={[0, -1.12, 0]}>
        <mesh castShadow receiveShadow position={[0, 0.03, 0]}>
          <cylinderGeometry args={[0.6, 0.68, 0.08, radialSegments]} />
          <meshPhysicalMaterial
            map={marbleTexture}
            color="#E5DDC8"
            roughness={0.42}
            metalness={0.0}
            clearcoat={0.22}
            clearcoatRoughness={0.45}
          />
        </mesh>
        <mesh castShadow receiveShadow position={[0, -0.02, 0]}>
          <cylinderGeometry args={[0.7, 0.7, 0.02, radialSegments]} />
          <meshPhysicalMaterial
            color="#D8CFB7"
            roughness={0.5}
            metalness={0.0}
            clearcoat={0.2}
            clearcoatRoughness={0.5}
          />
        </mesh>
      </group>

      {/* Gilt rim around the lip — low metalness so it does not mirror the env */}
      <mesh position={[0, 0.97, 0]}>
        <torusGeometry args={[0.59, 0.014, 24, 192]} />
        <meshStandardMaterial color="#B8965A" metalness={0.35} roughness={0.62} />
      </mesh>

      {/* Floating crystal orb above the urn */}
      <Float speed={0.6} rotationIntensity={0} floatIntensity={0.25} floatingRange={[-0.02, 0.02]}>
        <mesh ref={orbRef} position={[0, 1.85, 0]}>
          <sphereGeometry args={[0.32, quality === "low" ? 64 : 96, quality === "low" ? 64 : 96]} />
          {quality === "high" ? (
            <MeshTransmissionMaterial
              backside
              backsideThickness={0.4}
              thickness={0.5}
              chromaticAberration={0}
              anisotropicBlur={0.02}
              roughness={0.18}
              ior={1.38}
              distortion={0}
              distortionScale={0.2}
              temporalDistortion={0}
              transmission={0.9}
              clearcoat={0.4}
              attenuationColor="#FBF6E8"
              attenuationDistance={2.5}
              color="#FBF8F1"
            />
          ) : (
            <meshPhysicalMaterial
              color="#FBF8F1"
              transmission={0.9}
              roughness={0.08}
              ior={1.45}
              thickness={0.5}
              transparent
              opacity={0.85}
            />
          )}
        </mesh>
      </Float>

      {/* Gold leaf ring around the orb */}
      <Float speed={0.6} rotationIntensity={0} floatIntensity={0.25} floatingRange={[-0.02, 0.02]}>
        <mesh position={[0, 1.85, 0]} rotation-x={Math.PI / 2 - 0.15}>
          <torusGeometry args={[0.46, 0.007, 24, 240]} />
          <meshStandardMaterial
            color="#B8965A"
            metalness={0.4}
            roughness={0.55}
            emissive="#000000"
            emissiveIntensity={0}
          />
        </mesh>
      </Float>
    </group>
  );
}
